### ISSUE TITLE
Activate window vibrancy?

### ISSUE THREAD

**Issue by gingerbeardman** [material-theme/nova-material-theme-bugs#2]
Nova offers the ability for a theme to specify window vibrancy (this makes part of the window semi-opaque/transparent and blurred). 

In my experience the benefit of this allows a great difference between focused and unfocused windows. 

Without vibrancy only few items change on an inactive window—the colour of the window title changes, title bar icons, some ui labels—I personally find that is not enough to quickly identify the active window.

Do you have any thoughts about defining window vibrancy for Nova version of Material?

----

Here's a quick test, which window is active?

<img width="1312" alt="Screen shot 2024-10-21 at 19 07 43" src="https://github.com/user-attachments/assets/57ac3a26-4b39-45b6-bbe1-f3c69a1a2d90">

<img width="1268" alt="Screen shot 2024-10-21 at 19 07 13" src="https://github.com/user-attachments/assets/728d425f-1264-4c95-ba1b-833036d69c26">

**Comment by gingerbeardman** [comment]
And here's Monokai Pro (Spectrum) modified by me to have vibrancy switched on.

<img width="1312" alt="Screen shot 2024-10-21 at 19 09 57" src="https://github.com/user-attachments/assets/be075394-15c0-489e-884a-789eaf5809d0">

<img width="1268" alt="Screen shot 2024-10-21 at 19 09 59" src="https://github.com/user-attachments/assets/c2e26f0f-7aa1-41af-bbd9-a7684bddea4c">

**Comment by equinusocio** [comment]
Hello, the material theme for Nova is not under active development. We are waiting for the API to improve (like file icons and other UI changes). Also, the material theme is no longer open source and will become a paid extension, starting from the one for vscode. 

Said that, when we worked on Nova’s theme, the vibrancy was bugged. Atm I don’t have an active license for the editor since I don’t use it and we have no income to buy and test it. I will check if I can start a new trial to do some fix.

**Comment by gingerbeardman** [comment]
OK, no worries. 

Perhaps this repo could be archived? until such time when development resumes and it can be unarchived.

**Comment by equinusocio** [comment]
The theme is working, and still up to date. Just I don't add new features, as i'm focused on the main extension for vscode. There is no reason to archive this.

**Comment by gingerbeardman** [comment]
WOW

what a toxic attitude. blocked

**Comment by equinusocio** [comment]
Thanks
